options:
  formatter: stylish
  merge-default-rules: true

rules:
  indentation: 2
  no-ids: 1
  no-mergeable-selectors: 1
  no-important: 1
  no-attribute-selectors: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  no-color-literals: 0
  no-warn: 0
  no-transition-all: 0
